/** Saves generated bytes as a file download. */
export function downloadBytes(bytes, fileName, type = 'application/octet-stream') {
  const url = URL.createObjectURL(new Blob([bytes], { type }));
  const a = Object.assign(document.createElement('a'), { href: url, download: fileName, rel: 'noopener' });
  document.body.append(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 10_000);
}

/** Where Logic Pro looks for user Channel EQ presets. */
export const PRESET_FOLDER = '~/Music/Audio Music Apps/Plug-In Settings/Channel EQ';
